server:
  port: 8189
  servlet:
    context-path: /demo
jwt:
  secret: 984hg493gh0439rth0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 30m
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/db/security
#    url: jdbc:h2:file:.users;MODE=PostgresSQL
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
