
CREATE TABLE users (
    id 			        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username 			VARCHAR(250) UNIQUE NOT NULL,
    password 			VARCHAR(250) NOT NULL,
    email 				VARCHAR(40) UNIQUE,

    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS roles (
    id 			BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name 	VARCHAR(250) NOT NULL,

    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users_roles (
    user_id				BIGINT  NOT NULL,
    role_id				INTEGER NOT NULL,

    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (role_id) REFERENCES roles (id)
);


INSERT INTO users(username, password, email)
VALUES
    ('user', '$2a$12$CaiILFsfaCm.tHzxqftc8e/GmWbL1TYVhtrH3TJJ6WPUXiRKXcXdu', 'user@mail.ru'),
    ('admin', '$2a$12$CaiILFsfaCm.tHzxqftc8e/GmWbL1TYVhtrH3TJJ6WPUXiRKXcXdu', 'admin@mail.ru');

INSERT INTO roles(name)
VALUES
    ('ROLE_USER'),
    ('ROLE_ADMIN');

INSERT INTO users_roles (user_id, role_id)
VALUES
    (1, 1),
    (2, 2);